# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "3.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b2/97/5d42485e71dfc078108a86d6de8fa46db44a1a9295e89c5d6d4a06e23a62/markupsafe-3.0.2.tar.gz";
      sha256 = "1w1b1a5pskpqhx1mb53rgpv9srplhrrkr4hsl67f8rq1z3nx6mgf";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "a2wsgi" = super.buildPythonPackage rec {
    pname = "a2wsgi";
    version = "1.10.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/54/1e14731678ec375875c65df3d020714361230d3b8aa8188d2290d07dabe4/a2wsgi-1.10.8-py3-none-any.whl";
      sha256 = "1l4s17l0qh7yr8z303654rv1j6brkbzw3bfws2xycipah7pv7gbz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "aiohappyeyeballs" = super.buildPythonPackage rec {
    pname = "aiohappyeyeballs";
    version = "2.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0f/15/5bf3b99495fb160b63f95972b81750f18f7f4e02ad051373b669d17d44f2/aiohappyeyeballs-2.6.1-py3-none-any.whl";
      sha256 = "1f0z6c4iydxh09w5ka82556j11g4jzlq8bawkk4jbjvm9f7vljgk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "aiohttp" = super.buildPythonPackage rec {
    pname = "aiohttp";
    version = "3.11.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/18/31398875dc7b9815767370f60f44284155f2e1c1b87ec721c1b0ee61d1e5/aiohttp-3.11.15.tar.gz";
      sha256 = "02rdl2va6njn37gjz4wqvvh1ax7p84729smshi2wr3xcjbjs3fdr";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiohappyeyeballs"
      self."aiosignal"
      self."async-timeout"
      self."attrs"
      self."frozenlist"
      self."multidict"
      self."propcache"
      self."yarl"
    ];
  };
  "aiosignal" = super.buildPythonPackage rec {
    pname = "aiosignal";
    version = "1.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/6a/bc7e17a3e87a2985d3e8f4da4cd0f481060eb78fb08596c42be62c90a4d9/aiosignal-1.3.2-py2.py3-none-any.whl";
      sha256 = "199irfd9sxbk47mvb4421mvy7pcbqb802aqck0aifc4s827fbka5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."frozenlist"
    ];
  };
  "aiosqlite" = super.buildPythonPackage rec {
    pname = "aiosqlite";
    version = "0.21.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f5/10/6c25ed6de94c49f88a91fa5018cb4c0f3625f31d5be9f771ebe5cc7cd506/aiosqlite-0.21.0-py3-none-any.whl";
      sha256 = "1l6p4sr7pmwfvnbk3cgdmphxg497ir7bdwhnpbf56pzrax0cyj95";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "annotated-types" = super.buildPythonPackage rec {
    pname = "annotated-types";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/b6/6307fbef88d9b5ee7421e68d78a9f162e0da4900bc5f5793f6d3d0e34fb8/annotated_types-0.7.0-py3-none-any.whl";
      sha256 = "0lrab0f3lgvpbj79p178xd7cn6qkr2zz9w6lw3rw7fwg7asfh0hz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "anyio" = super.buildPythonPackage rec {
    pname = "anyio";
    version = "4.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a1/ee/48ca1a7c89ffec8b6a0c5d02b89c305671d5ffd8d3c94acf8b8c408575bb/anyio-4.9.0-py3-none-any.whl";
      sha256 = "0g6rqjlw0126i3qgphgj0hz1xd7kfs49fbmnpvvnmqynr90xaxlz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."exceptiongroup"
      self."idna"
      self."sniffio"
      self."typing-extensions"
    ];
  };
  "appdirs" = super.buildPythonPackage rec {
    pname = "appdirs";
    version = "1.4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl";
      sha256 = "0a5ib82s2335nhvq5rjh8hkimrwyw43xnshn3ds8lccrdg6xlhd8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "asgiref" = super.buildPythonPackage rec {
    pname = "asgiref";
    version = "3.8.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/e3/893e8757be2612e6c266d9bb58ad2e3651524b5b40cf56761e985a28b13e/asgiref-3.8.1-py3-none-any.whl";
      sha256 = "0isy6f816ir6i2jp5vka3nxq4px5ny36djzjri9gwclqhk63w7iy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "async-timeout" = super.buildPythonPackage rec {
    pname = "async-timeout";
    version = "5.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fe/ba/e2081de779ca30d473f21f5b30e0e737c438205440784c7dfc81efc2b029/async_timeout-5.0.1-py3-none-any.whl";
      sha256 = "0v77gzkjk90zg9d41jfap9j86v09bssrh8zcax2kb1gzcsaq1qrr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "25.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/77/06/bb80f5f86020c4551da315d78b3ab75e8228f89f0162f2c3a819e407941a/attrs-25.3.0-py3-none-any.whl";
      sha256 = "1hrv1vjc46jqmnb1bxn6zybrm283dw910d3q82jzw08p0g71hws2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "bentoml" = super.buildPythonPackage rec {
    pname = "bentoml";
    version = "1.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/57/c1/e6ec5d8b7672c47c69cd48361eba44c76e93f2b6ca07855e24c969142523/bentoml-1.4.7-py3-none-any.whl";
      sha256 = "146k1mrrgimnzpva9c376a81x1h3wj7rrzif3343wnqrnjcncacb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."a2wsgi"
      self."aiohttp"
      self."aiosqlite"
      self."attrs"
      self."cattrs"
      self."click"
      self."click-option-group"
      self."cloudpickle"
      self."fs"
      self."httpx"
      self."httpx-ws"
      self."jinja2"
      self."kantoku"
      self."numpy"
      self."nvidia-ml-py"
      self."opentelemetry-api"
      self."opentelemetry-instrumentation"
      self."opentelemetry-instrumentation-aiohttp-client"
      self."opentelemetry-instrumentation-asgi"
      self."opentelemetry-sdk"
      self."opentelemetry-semantic-conventions"
      self."opentelemetry-util-http"
      self."packaging"
      self."pathspec"
      self."pip-requirements-parser"
      self."prometheus-client"
      self."psutil"
      self."pydantic"
      self."python-dateutil"
      self."python-dotenv"
      self."python-json-logger"
      self."python-multipart"
      self."pyyaml"
      self."questionary"
      self."rich"
      self."schema"
      self."simple-di"
      self."starlette"
      self."tomli"
      self."tomli-w"
      self."uvicorn"
      self."watchfiles"
    ];
  };
  "cattrs" = super.buildPythonPackage rec {
    pname = "cattrs";
    version = "23.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3a/ba/05df14efaa0624fac6b1510e87f5ce446208d2f6ce50270a89b6268aebfe/cattrs-23.1.2-py3-none-any.whl";
      sha256 = "192hvqwqdvf8bkyf6cirr8d47r92y1h5lpkqb06ysyy138qi9fxj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."exceptiongroup"
      self."typing-extensions"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2025.1.31";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/38/fc/bce832fd4fd99766c04d1ee0eead6b0ec6486fb100ae5e74c1d91292b982/certifi-2025.1.31-py3-none-any.whl";
      sha256 = "1zl4dds31mwyj81hxrqb1nl9wn7vy9ldzg5j9mm04lm6cm2xny6a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "8.1.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/d4/7ebdbd03970677812aac39c869717059dbb71a4cfc033ca6e5221787892c/click-8.1.8-py3-none-any.whl";
      sha256 = "1ck3f812hql67a8bfafkq30xjqmvjzsd38hjcyh7h5fhpsxk5hb3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click-option-group" = super.buildPythonPackage rec {
    pname = "click-option-group";
    version = "0.5.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/27/bf74dc1494625c3b14dbcdb93740defd7b8c58dae3736be8d264f2a643fb/click_option_group-0.5.7-py3-none-any.whl";
      sha256 = "092wsd5ff6m6f97ac0d4qx391s453xnbsa8rz0bdkx3y74pzbfcn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
    ];
  };
  "cloudpickle" = super.buildPythonPackage rec {
    pname = "cloudpickle";
    version = "3.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/e8/64c37fadfc2816a7701fa8a6ed8d87327c7d54eacfbfb6edab14a2f2be75/cloudpickle-3.1.1-py3-none-any.whl";
      sha256 = "03imd2k6adyzrj3hxrc8z6v9fwlw188blh5dkpp334q3jm1a9if8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "deprecated" = super.buildPythonPackage rec {
    pname = "deprecated";
    version = "1.2.18";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/c6/ac0b6c1e2d138f1002bcf799d330bd6d85084fece321e662a14223794041/Deprecated-1.2.18-py2.py3-none-any.whl";
      sha256 = "1v4f05f1pl7ygha63nab47881zq9d8r8x24g84r2ldq0h9w12l5x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."wrapt"
    ];
  };
  "exceptiongroup" = super.buildPythonPackage rec {
    pname = "exceptiongroup";
    version = "1.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/02/cc/b7e31358aac6ed1ef2bb790a9746ac2c69bcb3c8588b41616914eb106eaf/exceptiongroup-1.2.2-py3-none-any.whl";
      sha256 = "0nvrlxd5i42ri3zd6ddi7xb478jbw4iy25pmz31bwf62678vj49i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "frozenlist" = super.buildPythonPackage rec {
    pname = "frozenlist";
    version = "1.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8f/ed/0f4cec13a93c02c47ec32d81d11c0c1efbadf4a471e3f3ce7cad366cbbd3/frozenlist-1.5.0.tar.gz";
      sha256 = "05xqnkqq7k95v5nfgq1kck78v4i36wjl5m3nx148770vwqlszmc1";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "fs" = super.buildPythonPackage rec {
    pname = "fs";
    version = "2.4.16";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/5c/a3d95dc1ec6cdeb032d789b552ecc76effa3557ea9186e1566df6aac18df/fs-2.4.16-py2.py3-none-any.whl";
      sha256 = "0p2lj6d7ylbxgd1b4phakq49xgnim20cxfmnw152dnncpgz68036";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."appdirs"
      self."setuptools"
      self."six"
    ];
  };
  "h11" = super.buildPythonPackage rec {
    pname = "h11";
    version = "0.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/04/ff642e65ad6b90db43e668d70ffb6736436c7ce41fcc549f4e9472234127/h11-0.14.0-py3-none-any.whl";
      sha256 = "0qd7z9p38dwx215048q708vd1sn2abdh1mb3hg66ii2ip324mzp3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "httpcore" = super.buildPythonPackage rec {
    pname = "httpcore";
    version = "1.0.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/87/f5/72347bc88306acb359581ac4d52f23c0ef445b57157adedb9aee0cd689d2/httpcore-1.0.7-py3-none-any.whl";
      sha256 = "1p8f8bnrir1d50s6z19jndca98qghgqrr7rx6syxaq627psgizx3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."h11"
    ];
  };
  "httpx" = super.buildPythonPackage rec {
    pname = "httpx";
    version = "0.28.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/39/e50c7c3a983047577ee07d2a9e53faf5a69493943ec3f6a384bdc792deb2/httpx-0.28.1-py3-none-any.whl";
      sha256 = "1barpaw8as8xb7b2bsmzdmdbq5nqljlq5jhlz3xcgy0hq76gq2fr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."anyio"
      self."certifi"
      self."httpcore"
      self."idna"
    ];
  };
  "httpx-ws" = super.buildPythonPackage rec {
    pname = "httpx-ws";
    version = "0.7.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/03/3d/2113a5c7af9a13663fa026882d0302ed4142960388536f885dacd6be7038/httpx_ws-0.7.2-py3-none-any.whl";
      sha256 = "18r7hid2y0j586kjbkpcxf5hdb6g608pwfmgy77dbp4nmbdzjyyx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."anyio"
      self."httpcore"
      self."httpx"
      self."wsproto"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/c6/c88e154df9c4e1a2a66ccf0005a88dfb2650c1dffb6f5ce603dfbd452ce3/idna-3.10-py3-none-any.whl";
      sha256 = "1lw72a5swas501zvkpd6dsryj5hzjijqxs3526kbp7151md1jvcl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "8.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/79/9d/0fb148dc4d6fa4a7dd1d8378168d9b4cd8d4560a6fbf6f0121c5fc34eb68/importlib_metadata-8.6.1-py3-none-any.whl";
      sha256 = "0pjjhybmpgs8y7b9fp00jh20srb27v5jasvw1pfdypz1q6897a02";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "jinja2" = super.buildPythonPackage rec {
    pname = "jinja2";
    version = "3.1.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/a1/3d680cbfd5f4b8f15abc1d571870c5fc3e594bb582bc3b64ea099db13e56/jinja2-3.1.6-py3-none-any.whl";
      sha256 = "0rrgdp707wfs11wk8prswvx6ma418sk16z6xql9hqba93x2y9v45";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "kantoku" = super.buildPythonPackage rec {
    pname = "kantoku";
    version = "0.18.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/06/6433998627f7d39fe97e01c581c337e1837394569078cd80f942d2cea2bb/kantoku-0.18.3-py3-none-any.whl";
      sha256 = "1bg1h74yp1q4cgjhc2hbhksjq830yf32wnmc50frbjp8blw7vpxx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."psutil"
      self."pyzmq"
      self."tornado"
    ];
  };
  "markdown-it-py" = super.buildPythonPackage rec {
    pname = "markdown-it-py";
    version = "3.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/d7/1ec15b46af6af88f19b8e5ffea08fa375d433c998b8a7639e76935c14f1f/markdown_it_py-3.0.0-py3-none-any.whl";
      sha256 = "1cfam2hw2bfjiwxf9038yj3cqrcpiw7c9n6q5hirdgb0bj21clim";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."mdurl"
    ];
  };
  "mdurl" = super.buildPythonPackage rec {
    pname = "mdurl";
    version = "0.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl";
      sha256 = "1y5qjqhmq2nm7xj6w5rrp503r7jhj7zr2qcnr6gs858nwm0ql044";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "multidict" = super.buildPythonPackage rec {
    pname = "multidict";
    version = "6.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a1/d4/4e0e25aabd94f289b7d47da8293a3563e73ac1a4f7e9caddf11b6eeaf52d/multidict-6.3.1.tar.gz";
      sha256 = "10qjw9hizdcqsssbhgr5j27g22h0ybg0d1kl49h76mgqwfpxc61y";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "numpy" = super.buildPythonPackage rec {
    pname = "numpy";
    version = "2.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/75/10dd1f8116a8b796cb2c737b674e02d02e80454bda953fa7e65d8c12b016/numpy-2.0.2.tar.gz";
      sha256 = "0y3fcd268cnrc8ipcmj1c082an4j4a4wj3dbcjlf500qxryrhg48";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "nvidia-ml-py" = super.buildPythonPackage rec {
    pname = "nvidia-ml-py";
    version = "12.570.86";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d8/a8/ec37169be4e2b7063b9076ed3fe0661e87335fbca665eed3f48c415cb234/nvidia_ml_py-12.570.86-py3-none-any.whl";
      sha256 = "0l8bbkli2xz7jkjwj11dlyadvdgkk21g29xjvh9vsnl4bbipv42q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "opentelemetry-api" = super.buildPythonPackage rec {
    pname = "opentelemetry-api";
    version = "1.31.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/c8/86557ff0da32f3817bc4face57ea35cfdc2f9d3bcefd42311ef860dcefb7/opentelemetry_api-1.31.1-py3-none-any.whl";
      sha256 = "18d03lqb3j5chw0imp89xl70r21mg2ilx3d6xqpa7j69f3sa648m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."deprecated"
      self."importlib-metadata"
    ];
  };
  "opentelemetry-instrumentation" = super.buildPythonPackage rec {
    pname = "opentelemetry-instrumentation";
    version = "0.41b0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ca/c6/09f554c655bc93b37e54915257236d2462a120d12b01cf4699e178a5f612/opentelemetry_instrumentation-0.41b0-py3-none-any.whl";
      sha256 = "11nkbc6gn2mhq83wl1hjbb0nxkji8ap4ba54j9cj187cbiqfby8f";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."opentelemetry-api"
      self."setuptools"
      self."wrapt"
    ];
  };
  "opentelemetry-instrumentation-aiohttp-client" = super.buildPythonPackage rec {
    pname = "opentelemetry-instrumentation-aiohttp-client";
    version = "0.41b0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/a6/55c6c65a94279ae50649ef6d362caaffc13b191ad1dde78b7007ec7e7549/opentelemetry_instrumentation_aiohttp_client-0.41b0-py3-none-any.whl";
      sha256 = "0vws77v8ydaqai00h4i36djd2mnfskwn39fihy8wymsyxs6x3l51";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."opentelemetry-api"
      self."opentelemetry-instrumentation"
      self."opentelemetry-semantic-conventions"
      self."opentelemetry-util-http"
      self."wrapt"
    ];
  };
  "opentelemetry-instrumentation-asgi" = super.buildPythonPackage rec {
    pname = "opentelemetry-instrumentation-asgi";
    version = "0.41b0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/12/3a8a0540e0de80c1dcf7a2845cbeef01d2b86483c5bd89b502422787b2bb/opentelemetry_instrumentation_asgi-0.41b0-py3-none-any.whl";
      sha256 = "08k4pryl2p7rgbgis3vrqmc8c763wh54kpg1pdx50l4wzfal2226";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."asgiref"
      self."opentelemetry-api"
      self."opentelemetry-instrumentation"
      self."opentelemetry-semantic-conventions"
      self."opentelemetry-util-http"
    ];
  };
  "opentelemetry-sdk" = super.buildPythonPackage rec {
    pname = "opentelemetry-sdk";
    version = "1.31.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/36/758e5d3746bc86a2af20aa5e2236a7c5aa4264b501dc0e9f40efd9078ef0/opentelemetry_sdk-1.31.1-py3-none-any.whl";
      sha256 = "1bkxiq54c5x0ga5g8zz1z49w1fyqq434wyyaz9xf68zj449h4bc8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."opentelemetry-api"
      self."opentelemetry-semantic-conventions"
      self."typing-extensions"
    ];
  };
  "opentelemetry-semantic-conventions" = super.buildPythonPackage rec {
    pname = "opentelemetry-semantic-conventions";
    version = "0.41b0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/aa/78/7a7508d16d32f92d6b206b2e367c5f044b3e652e7f385bbf17f49baad189/opentelemetry_semantic_conventions-0.41b0-py3-none-any.whl";
      sha256 = "1wmh5d4i601xkhxhql067wa1rh4pnk8mm4m4hf0rjl4yxn8l6h25";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "opentelemetry-util-http" = super.buildPythonPackage rec {
    pname = "opentelemetry-util-http";
    version = "0.41b0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4b/80/592edc50d116250f5e9eb60ae9ea5143ffde52e52f84642cec5175587ffe/opentelemetry_util_http-0.41b0-py3-none-any.whl";
      sha256 = "1rfygr8km729k2ag5dsl46zd0bnqnmji35qdaclzdc78w38py5ka";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "24.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/88/ef/eb23f262cca3c0c4eb7ab1933c3b1f03d021f2c48f54763065b6f0e321be/packaging-24.2-py3-none-any.whl";
      sha256 = "0nd7a421brjgd4prm8fbs8a6bcv4n1yplgxalgs02p16rnyb3aq9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pathspec" = super.buildPythonPackage rec {
    pname = "pathspec";
    version = "0.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/20/ff623b09d963f88bfde16306a54e12ee5ea43e9b597108672ff3a408aad6/pathspec-0.12.1-py3-none-any.whl";
      sha256 = "026cnk3hvsy7g65ll3nzi3rcc0bavazgg94hfjr27hd473hh7md0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pip-requirements-parser" = super.buildPythonPackage rec {
    pname = "pip-requirements-parser";
    version = "32.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/54/d0/d04f1d1e064ac901439699ee097f58688caadea42498ec9c4b4ad2ef84ab/pip_requirements_parser-32.0.1-py3-none-any.whl";
      sha256 = "09kmqmllfcbn72fc396vns2ncj5jz366y3qrbnhyg0vpcqmbqna6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."packaging"
      self."pyparsing"
    ];
  };
  "prometheus-client" = super.buildPythonPackage rec {
    pname = "prometheus-client";
    version = "0.21.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/c2/ab7d37426c179ceb9aeb109a85cda8948bb269b7561a0be870cc656eefe4/prometheus_client-0.21.1-py3-none-any.whl";
      sha256 = "00gk06h1bxwyc1c1rzpsl42v6895rjsq1zj0i64gix6n2324ajsr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prompt-toolkit" = super.buildPythonPackage rec {
    pname = "prompt-toolkit";
    version = "3.0.50";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e4/ea/d836f008d33151c7a1f62caf3d8dd782e4d15f6a43897f64480c2b8de2ad/prompt_toolkit-3.0.50-py3-none-any.whl";
      sha256 = "164ifzchkddipf7dirl9g5bfnmf50yirclgnry5djyg437mjfr4v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."wcwidth"
    ];
  };
  "propcache" = super.buildPythonPackage rec {
    pname = "propcache";
    version = "0.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/c8/fdc6686a986feae3541ea23dcaa661bd93972d3940460646c6bb96e21c40/propcache-0.3.1.tar.gz";
      sha256 = "1kvf5h1mpfzklxwf0iavx96a5jggvn7f29vmhfc90db56z1q1na0";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "psutil" = super.buildPythonPackage rec {
    pname = "psutil";
    version = "7.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/80/336820c1ad9286a4ded7e845b2eccfcb27851ab8ac6abece774a6ff4d3de/psutil-7.0.0.tar.gz";
      sha256 = "0mn42p9pzh0wynhk9i18iyvp8h54hbcsyczajmjcpv4blgmw7sbv";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pydantic" = super.buildPythonPackage rec {
    pname = "pydantic";
    version = "2.11.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/12/f9221a949f2419e2e23847303c002476c26fbcfd62dc7f3d25d0bec5ca99/pydantic-2.11.1-py3-none-any.whl";
      sha256 = "1f70aq5j60aq8gb8idmnzsqwdzk38g4f16w59nhj70czxrg42v2v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."annotated-types"
      self."pydantic-core"
      self."typing-extensions"
      self."typing-inspection"
    ];
  };
  "pydantic-core" = super.buildPythonPackage rec {
    pname = "pydantic-core";
    version = "2.33.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/05/91ce14dfd5a3a99555fce436318cc0fd1f08c4daa32b3248ad63669ea8b4/pydantic_core-2.33.0.tar.gz";
      sha256 = "1cqnsqypcfdg2chil7ybsx652wxf6anm10aapwy9qh5scbv8mss0";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "pygments" = super.buildPythonPackage rec {
    pname = "pygments";
    version = "2.19.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/0b/9fcc47d19c48b59121088dd6da2488a49d5f72dacf8262e2790a1d2c7d15/pygments-2.19.1-py3-none-any.whl";
      sha256 = "133dmda902c3wcg63c1lf1jwxfwkbb9nvarg4jwg9v2wsm5598cy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "3.2.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/e7/df2285f3d08fee213f2d041540fa4fc9ca6c2d44cf36d3a035bf2a8d2bcc/pyparsing-3.2.3-py3-none-any.whl";
      sha256 = "1kxzwbvmxj81y8y3wf0c16xi88wq4i551jjnndchpzfn0a796jd7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.9.0.post0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl";
      sha256 = "09q48zvsbagfa3w87zkd2c5xl54wmb9rf2hlr20j4a5fzxxvrcm8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "python-dotenv" = super.buildPythonPackage rec {
    pname = "python-dotenv";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/18/98a99ad95133c6a6e2005fe89faedf294a748bd5dc803008059409ac9b1e/python_dotenv-1.1.0-py3-none-any.whl";
      sha256 = "0pfmp4gmdxnl8my4akg7nnxhsjvmk1bdjqpmp8c6r4ck4ag1vh6p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-json-logger" = super.buildPythonPackage rec {
    pname = "python-json-logger";
    version = "3.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/08/20/0f2523b9e50a8052bc6a8b732dfc8568abbdc42010aef03a2d750bdab3b2/python_json_logger-3.3.0-py3-none-any.whl";
      sha256 = "1izf6lyspvfyx6v2r4rg6hi6s38wsv9miqgnr89lrcpzijp0z66x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "python-multipart" = super.buildPythonPackage rec {
    pname = "python-multipart";
    version = "0.0.20";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/45/58/38b5afbc1a800eeea951b9285d3912613f2603bdf897a4ab0f4bd7f405fc/python_multipart-0.0.20-py3-none-any.whl";
      sha256 = "017in6m3bv70ksnr5m70zgrk5inwihbkwahzw2gmh1jy6fld6qla";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "6.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/54/ed/79a089b6be93607fa5cdaedf301d7dfb23af5f25c398d5ead2525b063e17/pyyaml-6.0.2.tar.gz";
      sha256 = "0gmwggzm0j0iprx074g5hah91y2f68sfhhldq0f8crddj7ndk16m";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyzmq" = super.buildPythonPackage rec {
    pname = "pyzmq";
    version = "26.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3a/ed/c3876f3b3e8beba336214ce44e1efa1792dd537027cef24192ac2b077d7c/pyzmq-26.3.0.tar.gz";
      sha256 = "1cs3c970sq2qcdlsrz532wdl7bd0ghzp1z58720vgakg4fw6ikgi";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "questionary" = super.buildPythonPackage rec {
    pname = "questionary";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/3f/11dd4cd4f39e05128bfd20138faea57bec56f9ffba6185d276e3107ba5b2/questionary-2.1.0-py3-none-any.whl";
      sha256 = "1v5qp9bsskk94wlyf2hfk5hyx437mnln7ivq92785g38gcils5s4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."prompt-toolkit"
    ];
  };
  "rich" = super.buildPythonPackage rec {
    pname = "rich";
    version = "14.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0d/9b/63f4c7ebc259242c89b3acafdb37b41d1185c07ff0011164674e9076b491/rich-14.0.0-py3-none-any.whl";
      sha256 = "1q6pjp1qs1l3dqzrj57y7y95hknhwf748bylzz50kb0sjphr350w";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."markdown-it-py"
      self."pygments"
      self."typing-extensions"
    ];
  };
  "schema" = super.buildPythonPackage rec {
    pname = "schema";
    version = "0.7.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/1b/81855a88c6db2b114d5b2e9f96339190d5ee4d1b981d217fa32127bb00e0/schema-0.7.7-py2.py3-none-any.whl";
      sha256 = "1pjx4nsavvwvkk65yhk55vad8aq0c1xhjivv2pi78vpka1dnm5sx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "simple-di" = super.buildPythonPackage rec {
    pname = "simple-di";
    version = "0.1.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/6d/02014c8b1e34bae98b9b7fb5e9a4bc17aecdc28dfb08083e1fa9e4731b7d/simple_di-0.1.5-py3-none-any.whl";
      sha256 = "0id3nazmkbb48s4r01amqkdlris7vqdda7ap5ly9lf4gy5165yz3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl";
      sha256 = "0x1jdic712dylbnyiqdj4xyxrlx0gaacynmbmkfiym4hxn8z68a7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sniffio" = super.buildPythonPackage rec {
    pname = "sniffio";
    version = "1.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e9/44/75a9c9421471a6c4805dbf2356f7c181a29c1879239abab1ea2cc8f38b40/sniffio-1.3.1-py3-none-any.whl";
      sha256 = "18i50l85yppn9w1ily8m342yd577h0bg8y24hkfzvq7is4ca8v9g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "starlette" = super.buildPythonPackage rec {
    pname = "starlette";
    version = "0.46.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/4b/528ccf7a982216885a1ff4908e886b8fb5f19862d1962f56a3fce2435a70/starlette-0.46.1-py3-none-any.whl";
      sha256 = "09x2v30p1wxfavmxqdzcy958avdf5lx3y4vmb2r3h0bjsbclxivp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."anyio"
      self."typing-extensions"
    ];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/c2/61d3e0f47e2b74ef40a68b9e6ad5984f6241a942f7cd3bbfbdbd03861ea9/tomli-2.2.1-py3-none-any.whl";
      sha256 = "1k45vj5659ghprcb5rvxlx3z3jdrcbvzkvpk1jfpf224bwycfmfb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tomli-w" = super.buildPythonPackage rec {
    pname = "tomli-w";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/18/c86eb8e0202e32dd3df50d43d7ff9854f8e0603945ff398974c1d91ac1ef/tomli_w-1.2.0-py3-none-any.whl";
      sha256 = "146ghg4shjqp38dv06sp9i0kqzbjcsyil0fwr8gnjfq1il4hd0qq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tornado" = super.buildPythonPackage rec {
    pname = "tornado";
    version = "6.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/59/45/a0daf161f7d6f36c3ea5fc0c2de619746cc3dd4c76402e9db545bd920f63/tornado-6.4.2.tar.gz";
      sha256 = "02v2mlvr58xg0l0gh08nswl53z73wkf23sziggypk63ffjsdbflj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/86/39b65d676ec5732de17b7e3c476e45bb80ec64eb50737a8dce1a4178aba1/typing_extensions-4.13.0-py3-none-any.whl";
      sha256 = "1raqj2vw1sq6bz20k8w1m0f2ryaz9sax3fgv31yaj9b41p695pf8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-inspection" = super.buildPythonPackage rec {
    pname = "typing-inspection";
    version = "0.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/08/aa4fdfb71f7de5176385bd9e90852eaf6b5d622735020ad600f2bab54385/typing_inspection-0.4.0-py3-none-any.whl";
      sha256 = "0bw3hq9xd4yqxs804r8cjjn9zjxgwq8fd9zp35x3d9njzicjbrsh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "uvicorn" = super.buildPythonPackage rec {
    pname = "uvicorn";
    version = "0.34.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/14/33a3a1352cfa71812a3a21e8c9bfb83f60b0011f5e36f2b1399d51928209/uvicorn-0.34.0-py3-none-any.whl";
      sha256 = "1x1684azqz75bz9qznywlwnm34b95fzk0ylwl0lgl0i588wc0g82";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
      self."h11"
      self."typing-extensions"
    ];
  };
  "watchfiles" = super.buildPythonPackage rec {
    pname = "watchfiles";
    version = "1.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f5/26/c705fc77d0a9ecdb9b66f1e2976d95b81df3cae518967431e7dbf9b5e219/watchfiles-1.0.4.tar.gz";
      sha256 = "01bjf55bv3fsnpjrypydfgfip72z4lqbghh09wzdfqhhs7pp793b";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."anyio"
    ];
  };
  "wcwidth" = super.buildPythonPackage rec {
    pname = "wcwidth";
    version = "0.2.13";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fd/84/fd2ba7aafacbad3c4201d395674fc6348826569da3c0937e75505ead3528/wcwidth-0.2.13-py2.py3-none-any.whl";
      sha256 = "0nb89xwaqyhi09hqvnvb3hn047lgjkzjj60k6apq83alwi4919ix";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wrapt" = super.buildPythonPackage rec {
    pname = "wrapt";
    version = "1.17.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c3/fc/e91cc220803d7bc4db93fb02facd8461c37364151b8494762cc88b0fbcef/wrapt-1.17.2.tar.gz";
      sha256 = "1wr2s7mqh9ya4yg5p5inlc0v7qyrdcci6clxwxpl88hm9nfqwf21";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wsproto" = super.buildPythonPackage rec {
    pname = "wsproto";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/58/e860788190eba3bcce367f74d29c4675466ce8dddfba85f7827588416f01/wsproto-1.2.0-py3-none-any.whl";
      sha256 = "0dnpgl1jqkaalad5glyzigiavza2cv2qhy2741dxg1dmabbdvb5r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."h11"
    ];
  };
  "yarl" = super.buildPythonPackage rec {
    pname = "yarl";
    version = "1.18.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/9d/4b94a8e6d2b51b599516a5cb88e5bc99b4d8d4583e468057eaa29d5f0918/yarl-1.18.3.tar.gz";
      sha256 = "1qfj6kvdxr8bzka4lp0bh0xfgr5mzx7zzvj2jb4vcxxzbk20265c";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idna"
      self."multidict"
      self."propcache"
    ];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.21.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/1a/7e4798e9339adc931158c9d69ecc34f5e6791489d469f5e50ec15e35f458/zipp-3.21.0-py3-none-any.whl";
      sha256 = "0cfr7hmx88sji1ai52chvj1ivlgnqnxgy96fxdhg3499zl2vw6xc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
