# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "bentoml" = super.buildPythonPackage rec {
    pname = "bentoml";
    version = "1.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/57/c1/e6ec5d8b7672c47c69cd48361eba44c76e93f2b6ca07855e24c969142523/bentoml-1.4.7-py3-none-any.whl";
      sha256 = "146k1mrrgimnzpva9c376a81x1h3wj7rrzif3343wnqrnjcncacb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      pkgs.python3Packages."a2wsgi"
      pkgs.python3Packages."aiohttp"
      pkgs.python3Packages."aiosqlite"
      pkgs.python3Packages."attrs"
      pkgs.python3Packages."cattrs"
      pkgs.python3Packages."click"
      pkgs.python3Packages."click-option-group"
      pkgs.python3Packages."cloudpickle"
      pkgs.python3Packages."fs"
      pkgs.python3Packages."httpx"
      pkgs.python3Packages."httpx-ws"
      pkgs.python3Packages."jinja2"
      self."kantoku"
      pkgs.python3Packages."numpy"
      pkgs.python3Packages."nvidia-ml-py"
      pkgs.python3Packages."opentelemetry-api"
      pkgs.python3Packages."opentelemetry-instrumentation"
      pkgs.python3Packages."opentelemetry-instrumentation-aiohttp-client"
      pkgs.python3Packages."opentelemetry-instrumentation-asgi"
      pkgs.python3Packages."opentelemetry-sdk"
      pkgs.python3Packages."opentelemetry-semantic-conventions"
      pkgs.python3Packages."opentelemetry-util-http"
      pkgs.python3Packages."packaging"
      pkgs.python3Packages."pathspec"
      pkgs.python3Packages."pip-requirements-parser"
      pkgs.python3Packages."prometheus-client"
      pkgs.python3Packages."psutil"
      pkgs.python3Packages."pydantic"
      pkgs.python3Packages."python-dateutil"
      pkgs.python3Packages."python-dotenv"
      pkgs.python3Packages."python-json-logger"
      pkgs.python3Packages."python-multipart"
      pkgs.python3Packages."pyyaml"
      pkgs.python3Packages."questionary"
      pkgs.python3Packages."rich"
      pkgs.python3Packages."schema"
      pkgs.python3Packages."simple-di"
      pkgs.python3Packages."starlette"
      pkgs.python3Packages."tomli"
      pkgs.python3Packages."tomli-w"
      pkgs.python3Packages."uvicorn"
      pkgs.python3Packages."watchfiles"
      pkgs.python3Packages.python-multipart # needs to be fixed
    ];
  };
  "kantoku" = super.buildPythonPackage rec {
    pname = "kantoku";
    version = "0.18.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/06/6433998627f7d39fe97e01c581c337e1837394569078cd80f942d2cea2bb/kantoku-0.18.3-py3-none-any.whl";
      sha256 = "1bg1h74yp1q4cgjhc2hbhksjq830yf32wnmc50frbjp8blw7vpxx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      pkgs.python3Packages."psutil"
      pkgs.python3Packages."pyzmq"
      pkgs.python3Packages."tornado"
    ];
  };
}
